### ISSUE TITLE
Support custom query param for the authentication code

### ISSUE THREAD

**Issue by JJ11teen** [redactive-ai/redactive#17]
When a user is redirected back to the app callback during the authentication flow, the `code` to exchange for tokens is always returned using a `code` query param. It would be useful to be able to specify a different query param to pass the `code` in in cases when there are layered systems and `code` may already be a reserved query param (ie handled in a different way).

## Currently
The application generates a url to redirect the user to as so:
```js
const params = new URLSearchParams()
params.append("redirect_uri", redirect_uri)
const response = await fetch(`https://api.redactive.ai/api/auth/connect/${provider}/url?${params.toString()}`, {
    method: "POST",
    headers: {
        "Content-Type": "application/json",
        // Your API key should be stored securely and not commited to source control.
        "Authorization": "Bearer test_1234567"
    }
})
```
And the user is then returned to the application with the `code` to continue the auth flow available under the `code` param:
```js
const currentUrl = window.location.href;
const urlParams = new URLSearchParams(new URL(currentUrl).search);
const sign_in_code = urlParams.get('code');
```

## Proposed
The application is able to specify a query param it would like the code to be returned with:
```js
const params = new URLSearchParams()
params.append("redirect_uri", redirect_uri)
params.append("return_code_query_param", "a_different_value")
const response = await fetch(`https://api.redactive.ai/api/auth/connect/${provider}/url?${params.toString()}`, {
    method: "POST",
    headers: {
        "Content-Type": "application/json",
        // Your API key should be stored securely and not commited to source control.
        "Authorization": "Bearer test_1234567"
    }
})
```
And the user is then returned to the application with the `code` to continue the auth flow available under the `a_different_value` param:
```js
const currentUrl = window.location.href;
const urlParams = new URLSearchParams(new URL(currentUrl).search);
const sign_in_code = urlParams.get('a_different_value');
```
If `return_code_query_param` is not specified in the initial request, then `code` will be the default.

**Comment by kochie** [comment]
Feature has now been implemented by #18 in the python SDK. As well as release v1.4.45 internally. On the `POST /api/auth/connect/${provider}/url` there is an optional query parameter called `code_param_alias` if this is set the returning code at the end of the OAuth flow will be available under whatever the `code_param_alias` key is.
